# Generated by Django 5.2 on 2026-08-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='expires_at',
            field=models.DateField(blank=True, help_text='Leave blank if the offer has no expiry date.', null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('discount', 'Discount'), ('bogo', 'Buy 1 Get 1'), ('free', 'Free Offer'), ('endsoon', 'End Soon')], default='discount', max_length=20),
        ),
    ]
