# Generated by Django 5.2 on 2026-08-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_offer_expires_at_offer_offer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('discount', 'Discount'), ('bogo', 'Buy 1 Get 1'), ('free', 'Free Offer')], default='discount', max_length=20),
        ),
    ]
