# Generated by Django 5.2 on 2026-08-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_offer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='businesses/covers/'),
        ),
        migrations.AddField(
            model_name='business',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='businesses/logos/'),
        ),
    ]
