# Generated by Django 5.2 on 2026-08-07 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_business_cover_image_business_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='phone',
            field=models.CharField(default=919876543210, help_text='Include country code (e.g. +91512345678)', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='search_keywords',
            field=models.TextField(blank=True, help_text='Comma separated keywords'),
        ),
        migrations.AlterField(
            model_name='business',
            name='cover_image',
            field=models.ImageField(upload_to='businesses/covers/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='google_maps_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='business',
            name='logo',
            field=models.ImageField(upload_to='businesses/logos/'),
        ),
    ]
