# Generated by Django 5.2 on 2026-08-07 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_business_phone_business_search_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='image',
            field=models.ImageField(default='core/static/images/hero.jpg', upload_to='areas/'),
            preserve_default=False,
        ),
    ]
